run:
  modules-download-mode: readonly
  skip-dirs:
    - bin

linters:
  enable:
    - deadcode
    - gofmt
    - goimports
    - gosec
    - maligned
    - misspell
    - prealloc
    - stylecheck
    - unparam
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lukasmalkmus/expensify-go
  govet:
    check-shadowing: true
